name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allows manual execution

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full history is fetched
          lfs: true  # If using large files (optional)

      - name: Configure Git
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-github-username"

      - name: Pull latest changes from Hugging Face
        run: |
          git pull --rebase origin main || git reset --hard origin/main

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push https://Ziad0Adel:$HF_TOKEN@huggingface.co/spaces/Ziad0Adel/Search_Engine_llm main
